---

# Types of OreSpawner
ore_spawner_types:
  coal:

    # This is the item that you will hold in your hand to represent that Spawner. In short, the item in hand to pose Spawner.
    item_data:
      item: "minecraft:coal_ore"
      name: "Coal Ore"
      lore:
        - "Coal Ore"
        - "Level: %level%"

    # Block to spawn
    blocks:
      - "minecraft:stone"
      - "minecraft:coal_ore"

    # Spawn level
    levels:
      1:
        speed: 1 # Speed of spawn
      2:
        speed: 2 # Speed of spawn
      3:
        speed: 3 # Speed of spawn

...
